# Generated by Django 5.0.1 on 2024-01-22 17:45

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'regular'), (1, 'affiliate')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'active'), (1, 'inactive'), (2, 'investigate'), (3, 'blocked')], default=0)),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'user'), (1, 'admin'), (2, 'super_admin'), (3, 'top_manager')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-id',),
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
