# Generated by Django 5.0.1 on 2024-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
