# Generated by Django 5.0.1 on 2024-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deprecated_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
