# Generated by Django 5.0.1 on 2024-01-25 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_at', models.DateTimeField(null=True)),
                ('log_in_agent', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access_log',
                'verbose_name_plural': 'access_logs',
                'db_table': 'access_logs',
            },
        ),
    ]
