# Generated by Django 5.0.1 on 2024-01-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_table_accesslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslog',
            old_name='log_in_agent',
            new_name='user_agent',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='sign_in_count',
            field=models.IntegerField(default=0),
        ),
    ]
