# Generated by Django 5.0.2 on 2024-02-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notificationcontent_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='JwtBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('exp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'jwt black list',
                'verbose_name_plural': 'jwt black lists',
                'db_table': 'jwt_black_list',
            },
        ),
    ]
